VitalElement/AvalonStudio

AvalonStudio/AvalonStudio.Controls.Standard/SolutionExplorer/ProjectConfigurationDialogView.paml
AvalonStudio/AvalonStudio.Controls.Standard/SolutionExplorer/ProjectConfigurationDialogViewModel.cs
AvalonStudio/AvalonStudio.Controls.Standard/SolutionExplorer/ProjectViewModel.cs
AvalonStudio/AvalonStudio.Extensibility/AvalonStudio.Extensibility.csproj
AvalonStudio/AvalonStudio.Extensibility/Controls/ControlTheme.paml
AvalonStudio/AvalonStudio.Extensibility/Controls/ControlTheme.paml.cs
AvalonStudio/AvalonStudio.Extensibility/Controls/ToolControl.cs
AvalonStudio/AvalonStudio.Extensibility/Controls/ViewModelViewHost.cs
AvalonStudio/AvalonStudio.Extensibility/Controls/ViewModelViewHost.xaml
AvalonStudio/AvalonStudio.Extensibility/MVVM/ViewLocator.cs
AvalonStudio/AvalonStudio.Extensibility/Shell/IShell.cs
AvalonStudio/AvalonStudio.MiniShell/MinimalShell.cs
AvalonStudio/AvalonStudio.TextEditor/TextEditor.cs
AvalonStudio/AvalonStudio.TextEditor/TextEditorTheme.paml.cs
AvalonStudio/AvalonStudio/BootScreen.paml
AvalonStudio/AvalonStudio/Controls/DocumentTabControl.paml
AvalonStudio/AvalonStudio/Controls/DocumentTabControlViewModel.cs
AvalonStudio/AvalonStudio/Controls/Editor/EditorModel.cs
AvalonStudio/AvalonStudio/Controls/EditorView.xaml
AvalonStudio/AvalonStudio/Controls/EditorView.xaml.cs
AvalonStudio/AvalonStudio/Shell/Commands/CommentCommandDefinition.cs
AvalonStudio/AvalonStudio/Shell/Commands/RedoCommandDefinition.cs
AvalonStudio/AvalonStudio/Shell/Commands/UnCommentCommandDefinition.cs
AvalonStudio/AvalonStudio/Shell/Commands/UndoCommandDefinition.cs
AvalonStudio/AvalonStudio/ShellViewModel.cs

* Loading Control Themes only once via static constructors.
* Project configuration in DocTabs.

WIP: Configuration Pages in Doc Tabs

---

AvalonStudio/AvalonStudio.Controls.Standard/WelcomeScreen/WelcomeScreenViewModel.cs
AvalonStudio/AvalonStudio.Extensibility/Utils/StringUtils.cs

It allows adding a string to the end of a truncated string.

Slight adjustment to string.Truncate

---

AvalonStudio/AvalonStudio.Extensibility/Utils/StringUtils.cs

[Global]
Extension: string StripTags: Removes HTML from string with compiled Regex.

Adds more string utilities

---

README.md

Add more detailed build instructions, and link to the bleeding-edge binaries

Add more detailed instructions

---

AvalonStudio/AvalonStudio/App.paml
AvalonStudio/AvalonStudio/AvalonStudio.csproj
AvalonStudio/AvalonStudio/Controls/MetroWindow.paml
AvalonStudio/AvalonStudio/Controls/MetroWindowControlsTheme.paml
AvalonStudio/AvalonStudio/Controls/MetroWindowTheme.paml
AvalonStudio/AvalonStudio/Themes/Accents/DarkAccent.xaml

fade window controls on hover, also add a customizable accent

[ui tweak] fade window controls on hover

---

AvalonStudio/AvalonStudio.Debugging.GDB.JLink/JLinkDebugAdaptor.cs
AvalonStudio/AvalonStudio.Debugging.GDB.OpenOCD/OpenOCD.cs
AvalonStudio/AvalonStudio.Debugging.GDB/GDBDebugger.cs
AvalonStudio/AvalonStudio.Toolchains.Clang/ClangToolchain.cs
AvalonStudio/AvalonStudio.Toolchains.GCC/GCCToolchain.cs
AvalonStudio/AvalonStudio.Toolchains.Llilum/LlilumToolchain.cs

Only check if the compiler / debugger executables exist if the Path is

---

AvalonStudio/AvalonStudio/MainWindow.paml

Dependent on https://github.com/AvaloniaUI/Avalonia/pull/805

WIP: Start maximized and dont cover taskbar.

---

AvalonStudio/AvalonStudio.Extensibility.Tests/AvalonStudio.Extensibility.Tests.csproj
AvalonStudio/AvalonStudio.Extensibility.Tests/Properties/AssemblyInfo.cs
AvalonStudio/AvalonStudio.Extensibility.Tests/UnsavedFileUnitTests.cs
AvalonStudio/AvalonStudio.Extensibility.Tests/packages.config
AvalonStudio/AvalonStudio.Extensibility/Platform/Platform.cs
AvalonStudio/AvalonStudio.sln

Fix unsaved files getting out of sync

---

AvalonStudio/AvalonStudio.Debugging/WatchViewModel.cs
AvalonStudio/AvalonStudio.Extensibility.Tests/FilePathComparisonTests.cs
AvalonStudio/AvalonStudio.Extensibility/Platform/Platform.cs
AvalonStudio/AvalonStudio.TextEditor/Rendering/TextView.paml

fixed unable to click breakpoints.

fixes path comparison against null crashing,

---

AvalonStudio/AvalonStudio.Toolchains.GCC/GCCToolchain.cs

provisioning would be necessary.

dont cause provisioning when compiling, unless we are executable then

---

AvalonStudio/AvalonStudio.Controls.Standard/WelcomeScreen/NewsFeed.cs
AvalonStudio/AvalonStudio.Controls.Standard/WelcomeScreen/RecentProject.cs
AvalonStudio/AvalonStudio.Controls.Standard/WelcomeScreen/RecentProjectViewModel.cs
AvalonStudio/AvalonStudio.Controls.Standard/WelcomeScreen/VideoFeed.cs
AvalonStudio/AvalonStudio.Controls.Standard/WelcomeScreen/WelcomeScreenViewModel.cs

Formats welcome screen code consistent with .net formatting style.
Added live update of welcome screen recent project order.
Most recently opened project now goes to the top.

formatting and fixes to welcome screen.

---

AvalonStudio/buildmono.sh
AvalonStudio/dependencies.sh

Also cleaned up the scripts in general.

Modified Shell Scripts to support Ubuntu as well as Arch, and can be extended easily to other distributions.

---

AvalonStudio/AvalonStudio.Extensibility/Projects/FileSystemProject.cs

https://github.com/dotnet/corefx/issues/21934

check if a file exists on unix, this is a bug in CoreFx.

---

AvalonStudio/AvalonStudio.Controls.Standard/CodeEditor/IntellisenseManager.cs

by limiting the queue size to 1 element.

prevent intellisense queue from building up.

---

AvalonStudio/AvalonStudio.Debugging/DisassemblyViewModel.cs

fixes disassembly mixmode. At least when code is not optimized.

Fix mixed mode dissasembly

---

AvalonStudio/AvalonStudio/Controls/DocumentTabControlViewModel.cs
AvalonStudio/AvalonStudio/ShellViewModel.cs

much simpler, now just keep a single list.

fix caching leading to documents not on screen,

---

packages/deb/DEBIAN/control
packages/package-debian.sh

The script uses git describe --tags to get the version number.

[PACKAGE] Added support for building debian packages easily.

---

README.md

Avalonia Studio is supporting the released version of .NET Core 2, right?

README: update for .NET Core 2 release

---

AvalonStudio/AvalonStudio.Controls.Standard/SolutionExplorer/Commands/CloseSolutionCommandDefinition.cs
AvalonStudio/AvalonStudio.Controls.Standard/SolutionExplorer/ProjectViewModel.cs
AvalonStudio/AvalonStudio.Extensibility/Shell/IShell.cs
AvalonStudio/AvalonStudio/Controls/DocumentTabControlViewModel.cs
AvalonStudio/AvalonStudio/ShellViewModel.cs

also fix temporary tab closing.

close all documents when project is removed or when solution changes

---

AvalonStudio/AvalonStudio.Controls.Standard/ExtensionManagerDialog/ExtensionManagerDialogView.paml
AvalonStudio/AvalonStudio.Controls.Standard/ExtensionManagerDialog/ExtensionManagerDialogView.paml.cs
AvalonStudio/AvalonStudio.Controls.Standard/ExtensionManagerDialog/ExtensionManagerDialogViewModel.cs
AvalonStudio/AvalonStudio.Extensibility/Converters/BitmapValueConverter.cs
AvalonStudio/AvalonStudio.Extensibility/ExtensionManager.cs
AvalonStudio/AvalonStudio.Extensibility/ExtensionManifest.cs
AvalonStudio/AvalonStudio.Extensibility/ExtensionManifestExtensions.cs
AvalonStudio/AvalonStudio.Extensibility/IExtensionManifest.cs
AvalonStudio/AvalonStudio.Extensibility/Utils/SerializedObject.cs
AvalonStudio/AvalonStudio/App.paml.cs
AvalonStudio/AvalonStudio/Shell/Commands/ExtensionsCommandDefinition.cs
AvalonStudio/AvalonStudio/Shell/MenuDefinitions.cs
AvalonStudio/AvalonStudio/Styles/GlobalStyles.xaml

- Added an extension manager dialog.
- Improved extensions model.

Added an extension manager dialog

---

AvalonStudio/AvalonStudio.Controls.Standard/SolutionExplorer/SolutionExplorerViewModel.cs
AvalonStudio/AvalonStudio.Extensibility/Projects/AvalonStudioSolutionType.cs
AvalonStudio/AvalonStudio.Extensibility/Projects/ExportSolutionTypeAttribute.cs
AvalonStudio/AvalonStudio.Extensibility/Projects/ISolutionType.cs
AvalonStudio/AvalonStudio.Extensibility/Projects/ISolutionTypeMetadata.cs
AvalonStudio/AvalonStudio.Extensibility/Projects/SolutionTypeMetadata.cs
AvalonStudio/AvalonStudio.Extensibility/Projects/VisualStudioSolution.cs
AvalonStudio/AvalonStudio.Extensibility/Projects/VisualStudioSolutionType.cs
AvalonStudio/AvalonStudio.Extensibility/Shell/IShell.cs
AvalonStudio/AvalonStudio.MiniShell/MinimalShell.cs
AvalonStudio/AvalonStudio/Controls/StatusBarViewModel.cs
AvalonStudio/AvalonStudio/ShellViewModel.cs

- Changed solution types loading to use MEF.

Changed solution types loading to use MEF

---

AvalonStudio/AvalonStudio.Extensibility/TestFrameworks/ExportTestFrameworkAttribute.cs
AvalonStudio/AvalonStudio.Extensibility/TestFrameworks/ITestFramework.cs
AvalonStudio/AvalonStudio.MiniShell/MinimalShell.cs
AvalonStudio/AvalonStudio.TestFrameworks.Catch/AvalonStudio.TestFrameworks.Catch.csproj
AvalonStudio/AvalonStudio.TestFrameworks.Catch/CatchTestFramework.cs
AvalonStudio/AvalonStudio/ShellViewModel.cs

- Changed test frameworks loading to use MEF.

Changed test frameworks loading to use MEF

---

AvalonStudio/AvalonStudio.Controls.Standard/SolutionExplorer/NewProjectDialogViewModel.cs
AvalonStudio/AvalonStudio.Controls.Standard/SolutionExplorer/SolutionParentViewModel.cs
AvalonStudio/AvalonStudio.Extensibility.Tests/TestProject.cs
AvalonStudio/AvalonStudio.Extensibility.Tests/VisualStudioSolutionTests.cs
AvalonStudio/AvalonStudio.Extensibility/Projects/AvalonStudioSolution.cs
AvalonStudio/AvalonStudio.Extensibility/Projects/ExportProjectTypeAttribute.cs
AvalonStudio/AvalonStudio.Extensibility/Projects/FileSystemProject.cs
AvalonStudio/AvalonStudio.Extensibility/Projects/IProject.cs
AvalonStudio/AvalonStudio.Extensibility/Projects/IProjectType.cs
AvalonStudio/AvalonStudio.Extensibility/Projects/IProjectTypeMetadata.cs
AvalonStudio/AvalonStudio.Extensibility/Projects/ISolution.cs
AvalonStudio/AvalonStudio.Extensibility/Projects/Project.cs
AvalonStudio/AvalonStudio.Extensibility/Projects/ProjectTypeMetadata.cs
AvalonStudio/AvalonStudio.Extensibility/Projects/SolutionExtensions.cs
AvalonStudio/AvalonStudio.Extensibility/Projects/UnresolvedReference.cs
AvalonStudio/AvalonStudio.Extensibility/Projects/VisualStudioSolution.cs
AvalonStudio/AvalonStudio.Extensibility/Shell/IShell.cs
AvalonStudio/AvalonStudio.Extensibility/TestFrameworks/ExportTestFrameworkAttribute.cs
AvalonStudio/AvalonStudio.LanguageSupport.TypeScript/Projects/TypeScriptProject.cs
AvalonStudio/AvalonStudio.MiniShell/MinimalShell.cs
AvalonStudio/AvalonStudio.Projects.CPlusPlus/CPlusPlusProject.cs
AvalonStudio/AvalonStudio.Projects.CPlusPlus/CPlusPlusProjectType.cs
AvalonStudio/AvalonStudio.Projects.OmniSharp/OmniSharpProject.cs
AvalonStudio/AvalonStudio.Projects.OmniSharp/ProjectTypes/CSharpProjectType.cs
AvalonStudio/AvalonStudio.Projects.OmniSharp/ProjectTypes/DotNetCoreCSharpProjectType.cs
AvalonStudio/AvalonStudio/ShellViewModel.cs

- Changed project type loading to use MEF.

Changed project type loading to use MEF

---

AvalonStudio/AvalonStudio.Controls.Standard/SolutionExplorer/NewProjectDialogView.paml
AvalonStudio/AvalonStudio.Controls.Standard/SolutionExplorer/NewProjectDialogViewModel.cs
AvalonStudio/AvalonStudio.Extensibility/Templating/TemplateManager.cs

- Template loading improvements and fixes.

Template loading improvements and fixes

---

AvalonStudio/AvalonStudio.Debugging.GDB.JLink/JLinkDebugger.cs
AvalonStudio/AvalonStudio.Debugging.GDB.Local/LocalGdbDebugger.cs
AvalonStudio/AvalonStudio.Debugging.GDB.Remote/RemoteGdbDebugger.cs
AvalonStudio/AvalonStudio.Debugging/IDebugger.cs
AvalonStudio/AvalonStudio.Extensibility/Debugging/ExportDebuggerAttribute.cs
AvalonStudio/AvalonStudio.Extensibility/Debugging/IDebugger.cs
AvalonStudio/AvalonStudio.MiniShell/MinimalShell.cs
AvalonStudio/AvalonStudio.Projects.OmniSharp/Debugger/DotNetCoreDebugSessionProvider.cs
AvalonStudio/AvalonStudio/ShellViewModel.cs

- Changed debugger loading to use MEF.

Changed debugger loading to use MEF

---

AvalonStudio/AvalonStudio.Controls.Standard.Tests/TestLanguageService.cs
AvalonStudio/AvalonStudio.Controls.Standard/CodeEditor/CodeEditor.cs
AvalonStudio/AvalonStudio.Extensibility/Languages/ExportLanguageServiceAttribute.cs
AvalonStudio/AvalonStudio.Extensibility/Languages/ILanguageService.cs
AvalonStudio/AvalonStudio.Extensibility/Languages/ILanguageServiceMetadata.cs
AvalonStudio/AvalonStudio.Extensibility/Languages/LanguageServiceMetadata.cs
AvalonStudio/AvalonStudio.Extensibility/Projects/FileSystemFile.cs
AvalonStudio/AvalonStudio.Extensibility/Projects/ISourceFile.cs
AvalonStudio/AvalonStudio.Extensibility/Shell/IShell.cs
AvalonStudio/AvalonStudio.LanguageSupport.TypeScript/LanguageService/TypeScriptLanguageService.cs
AvalonStudio/AvalonStudio.Languages.CPlusPlus/CPlusPlusLanguageService.cs
AvalonStudio/AvalonStudio.Languages.CSharp/CSharpLanguageService.cs
AvalonStudio/AvalonStudio.Languages.Xaml/XamlLanguageService.cs
AvalonStudio/AvalonStudio.Languages.Xaml/XmlLanguageService.cs
AvalonStudio/AvalonStudio.MiniShell/MinimalShell.cs
AvalonStudio/AvalonStudio/ShellViewModel.cs

- Changed language services loading to use MEF.
I'll implement content types in a separate PR, because I'm still not sure how they should be registered, but I already added content type metadata to language services in this PR.

Changed language services loading to use MEF

---

AvalonStudio/AvalonStudio/App.paml.cs

Fixed app initialisation

---

AvalonStudio/AvalonStudio.Controls.Standard/CodeEditor/CodeEditor.cs
AvalonStudio/AvalonStudio.Extensibility/Languages/ContentTypeMetadata.cs
AvalonStudio/AvalonStudio.Extensibility/Languages/ContentTypeService.cs
AvalonStudio/AvalonStudio.Extensibility/Languages/ExportContentTypeAttribute.cs
AvalonStudio/AvalonStudio.Extensibility/Languages/ExportContractNames.cs
AvalonStudio/AvalonStudio.Extensibility/Languages/ExportLanguageServiceAttribute.cs
AvalonStudio/AvalonStudio.Extensibility/Languages/FileExtensionsAttribute.cs
AvalonStudio/AvalonStudio.Extensibility/Languages/IContentType.cs
AvalonStudio/AvalonStudio.Extensibility/Languages/IContentTypeService.cs
AvalonStudio/AvalonStudio.Extensibility/Languages/ILanguageServiceMetadata.cs
AvalonStudio/AvalonStudio.Extensibility/Languages/LanguageServiceMetadata.cs
AvalonStudio/AvalonStudio.Extensibility/Projects/FileSystemFile.cs
AvalonStudio/AvalonStudio.Extensibility/Projects/ISourceFile.cs
AvalonStudio/AvalonStudio.Languages.CPlusPlus/CPlusPlusLanguageService.cs
AvalonStudio/AvalonStudio.Languages.CPlusPlus/ContentCapabilities.cs
AvalonStudio/AvalonStudio.Languages.CPlusPlus/ContentTypes.cs
AvalonStudio/AvalonStudio.Languages.CSharp/CSharpLanguageService.cs
AvalonStudio/AvalonStudio.Languages.CSharp/ContentCapabilities.cs
AvalonStudio/AvalonStudio.Languages.CSharp/ContentTypes.cs
AvalonStudio/AvalonStudio.Languages.CSharp/MetaDataFile.cs
AvalonStudio/AvalonStudio.Languages.Xaml/ContentCapabilities.cs
AvalonStudio/AvalonStudio.Languages.Xaml/ContentTypes.cs
AvalonStudio/AvalonStudio.Languages.Xaml/XamlLanguageService.cs
AvalonStudio/AvalonStudio.Languages.Xaml/XmlLanguageService.cs
AvalonStudio/AvalonStudio/ShellViewModel.cs

- Implemented content type system for the code editor.
Each content type represents a language, and can have file extensions associated with it. It also defines a set of capabilities, which are used to evaluate if a language service component is applicable to that content type or not.

Implemented content type system for the code editor

---

AvalonStudio/AvalonStudio.Extensibility.Tests/TestProject.cs
AvalonStudio/AvalonStudio.Extensibility/Projects/FileSystemProject.cs
AvalonStudio/AvalonStudio.Extensibility/Projects/IProject.cs
AvalonStudio/AvalonStudio.Extensibility/Projects/UnresolvedReference.cs
AvalonStudio/AvalonStudio.Extensibility/Shell/IShell.cs
AvalonStudio/AvalonStudio.Extensibility/Toolchains/ExportToolchainAttribute.cs
AvalonStudio/AvalonStudio.Extensibility/Toolchains/IToolchain.cs
AvalonStudio/AvalonStudio.LanguageSupport.TypeScript/Projects/TypeScriptProject.cs
AvalonStudio/AvalonStudio.LanguageSupport.TypeScript/Toolchain/TypeScriptToolchain.cs
AvalonStudio/AvalonStudio.MiniShell/MinimalShell.cs
AvalonStudio/AvalonStudio.Projects.CPlusPlus/CPlusPlusProject.cs
AvalonStudio/AvalonStudio.Projects.CPlusPlus/ToolchainSettingsFormViewModel.cs
AvalonStudio/AvalonStudio.Projects.OmniSharp/OmniSharpProject.cs
AvalonStudio/AvalonStudio.Projects.OmniSharp/Toolchain/MSBuildToolchain.cs
AvalonStudio/AvalonStudio.Toolchains.Clang/ClangToolchain.cs
AvalonStudio/AvalonStudio.Toolchains.CustomGCC/CustomGCCToolchain.cs
AvalonStudio/AvalonStudio.Toolchains.GCC/CompileSettingsFormViewModel.cs
AvalonStudio/AvalonStudio.Toolchains.GCC/GCCToolchain.cs
AvalonStudio/AvalonStudio.Toolchains.GCC/LinkerSettingsFormViewModel.cs
AvalonStudio/AvalonStudio.Toolchains.LocalGCC/LocalGCCToolchain.cs
AvalonStudio/AvalonStudio.Toolchains.PublishedGCC/PublishedGCCToolchain.cs
AvalonStudio/AvalonStudio.Toolchains.STM32/STM32GCCToolchain.cs
AvalonStudio/AvalonStudio.Toolchains.Standard/StandardToolchain.cs
AvalonStudio/AvalonStudio/ShellViewModel.cs
AvalonStudio/AvalonStudioBuild/Program.cs

- Changed toolchain loading to use MEF.
- Renamed `IToolChain` to "IToolchain".
- Renamed `StandardToolChain` to `StandardToolchain`.

Changed toolchain loading to use MEF

---

README.md

IMO, it's easier to follow this way.

Organize build instructions

---

AvalonStudio/AvalonStudio/Controls/MetroWindow.cs

Fix for issue [#665 Fix Grabbing Header](https://github.com/VitalElement/AvalonStudio/issues/665)

Fix grabbing header

---

Directory.Build.targets

- Unify package versions. Even if a different version is specified in the project file, it will be updated to the one specified in `Directory.Build.targets`.

Unify package versions.

---

AvalonStudio/AvalonStudio.Extensibility/AvalonStudio.Extensibility.csproj
AvalonStudio/AvalonStudio.Languages.CPlusPlus/AvalonStudio.Languages.CPlusPlus.csproj
AvalonStudio/AvalonStudio.Languages.CSharp/AvalonStudio.Languages.CSharp.csproj
AvalonStudio/AvalonStudio.Studio/AvalonStudio.Studio.csproj
AvalonStudio/AvalonStudio/AvalonStudio.csproj
Directory.Build.props
Directory.Build.targets

Project file cleanup

---

AvalonStudio/AvalonStudio.Extensibility/Editor/CodeEditorViewModel.cs
AvalonStudio/AvalonStudio.Extensibility/Languages/ContentTypeService.cs
AvalonStudio/AvalonStudio.Extensibility/Languages/ExportLanguageServiceProviderAttribute.cs
AvalonStudio/AvalonStudio.Extensibility/Languages/ILanguageServiceProvider.cs
AvalonStudio/AvalonStudio.Extensibility/Languages/LanguageServiceProviderMetadata.cs
AvalonStudio/AvalonStudio.Extensibility/Studio/IStudio.cs
AvalonStudio/AvalonStudio.LanguageSupport.TypeScript/LanguageService/ContentCapabilities.cs
AvalonStudio/AvalonStudio.LanguageSupport.TypeScript/LanguageService/ContentTypes.cs
AvalonStudio/AvalonStudio.LanguageSupport.TypeScript/LanguageService/TypeScriptLanguageService.cs
AvalonStudio/AvalonStudio.LanguageSupport.TypeScript/LanguageService/TypeScriptLanguageServiceProvider.cs
AvalonStudio/AvalonStudio.Languages.CPlusPlus/CPlusPlusLanguageService.cs
AvalonStudio/AvalonStudio.Languages.CPlusPlus/CPlusPlusLanguageServiceProvider.cs
AvalonStudio/AvalonStudio.Languages.CSharp/CSharpLanguageService.cs
AvalonStudio/AvalonStudio.Languages.CSharp/CSharpLanguageServiceProvider.cs
AvalonStudio/AvalonStudio.Languages.Xaml/XamlLanguageService.cs
AvalonStudio/AvalonStudio.Languages.Xaml/XamlLanguageServiceProvider.cs
AvalonStudio/AvalonStudio.Languages.Xaml/XmlLanguageService.cs
AvalonStudio/AvalonStudio.Languages.Xaml/XmlLanguageServiceProvider.cs
AvalonStudio/AvalonStudio.Studio/StudioViewModel.cs

- Created `ILanguageServiceProvider` so that language services aren't shared.

Created ILanguageServiceProvider so that language services aren't shared

---

.gitignore
AvalonStudio/AvalonStudio.Extensibility/AvalonStudio.Extensibility.csproj
AvalonStudio/AvalonStudio.Sdk/AvalonStudio.Sdk.csproj
AvalonStudio/AvalonStudio.Sdk/GenerateExtensionManifest.cs
AvalonStudio/AvalonStudio.Sdk/build/AvalonStudio.Sdk.targets
AvalonStudio/AvalonStudio.sln

- Added SDK for AvalonStudio extensions.

Added SDK for AvalonStudio extensions

---

AvalonStudio/AvalonStudio.Controls.Standard/AvalonStudio.Controls.Standard.csproj
AvalonStudio/AvalonStudio.Debugging/AvalonStudio.Debugging.csproj
AvalonStudio/AvalonStudio.Extensibility/AvalonStudio.Extensibility.csproj
AvalonStudio/AvalonStudio.Languages.CPlusPlus/AvalonStudio.Languages.CPlusPlus.csproj
AvalonStudio/AvalonStudio.Languages.Xaml/AvaloniaPreviewer.cs
AvalonStudio/AvalonStudio.Languages.Xaml/RemoteWidget.cs
AvalonStudio/AvalonStudio.Toolchains.CustomGCC/AvalonStudio.Toolchains.CustomGCC.csproj
AvalonStudio/AvalonStudio.Toolchains.GCC/AvalonStudio.Toolchains.GCC.csproj
AvalonStudio/AvalonStudio.Toolchains.LocalGCC/AvalonStudio.Toolchains.LocalGCC.csproj
AvalonStudio/AvalonStudio.Toolchains.PublishedGCC/AvalonStudio.Toolchains.PublishedGCC.csproj
AvalonStudio/AvalonStudio.Toolchains.STM32/AvalonStudio.Toolchains.STM32.csproj
AvalonStudio/AvalonStudio/AvalonStudio.csproj
Directory.Build.targets

wip: add zooming and interactivity to avalonia previewer
